name: Deploy to Production

on:
  push:
    branches:    
      - 'release**'  # Push events to branches matching refs/heads/releases/*

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
