name: Run Looker Data Tests and Content Validator
on:
  push:
    branches:    
    - 'dev-looker-*'

env:
  LOOKERSDK_API_VERSION: ${{ secrets.LOOKERSDK_API_VERSION }}
  LOOKERSDK_BASE_URL: ${{ secrets.LOOKERSDK_BASE_URL }}
  LOOKERSDK_CLIENT_ID: ${{ secrets.LOOKERSDK_CLIENT_ID }}
  LOOKERSDK_CLIENT_SECRET: ${{ secrets.LOOKERSDK_CLIENT_SECRET }}
  LOOKERSDK_TIMEOUT: ${{ secrets.LOOKERSDK_TIMEOUT }}
  LOOKERSDK_VERIFY_SSL: ${{ secrets.LOOKERSDK_VERIFY_SSL }}

jobs:
  run_looker_data_tests_and_content_validator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.6
    - name: Install dependencies
      run: |
        pwd
        ls -la
        python -m pip install --upgrade pip
        pip install -r .github/actions/requirements.txt
    - name: Run test
      run: |
        python .github/actions/run_tests.py ${{ github.ref }} ${{ secrets.PROJECT_ID }}
